---
- name: Ansible Exemplar - REST Call for Asteroid Information from NASA
  hosts: localhost
  vars:
    api_key: "hGJYs36dXpCUTh2JhC9coPuNbyypDOeGaKYlnCW0"
    start_date: "2019-07-07"
    end_date: "2019-07-14"
    base_url: "https://api.nasa.gov/neo/rest/v1/feed"
    get_url: "{{ base_url }}?{{ start_date }}&{{ end_date }}&api_key={{ api_key }}"
  tasks:
    - name: Get Asteroid information
      uri:
        url: "{{ get_url }}"
        method: GET
        validate_certs: no
        follow_redirects: all
        return_content: yes
        body_format: json
      register: asteroid_output
      delegate_to: localhost

    - debug: var=asteroid_output

    - name: Save all Asteroid Output in its raw format
      local_action:
        copy content="{{ asteroid_output }}"
        dest="RESTGET-raw-output.txt"

    - name: Save only the data in the json key of Asteroid Output
      local_action: copy content="{{ asteroid_output.json }}" dest="RESTGET-json-output.txt"

    - name: Save all Asteroid Output after running it through the Ansible to_nice_json filter
      local_action: copy content="{{ asteroid_output | to_nice_json }}" dest="RESTGET-nice-output.json"